services:
  web:
    image: ghcr.io/seanmorley15/adventurelog-frontend:development
    container_name: adventurelog-frontend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8015:3000"
    depends_on:
      - server

  db:
    image: postgis/postgis:15-3.3
    container_name: adventurelog-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    image: ghcr.io/seanmorley15/adventurelog-backend:development
    container_name: adventurelog-backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8016:80"
    depends_on:
      - db
    volumes:
      - adventurelog_media:/code/media/

volumes:
  postgres_data:
  adventurelog_media:
