services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://adventurelog:PO24VjITwGgk@db:5432/adventurelog
      # ORIGIN is only necessary when not using a reverse proxy or hosting that includes https
      - ORIGIN=http://localhost:3000
    depends_on:
      - db
    volumes:
    - ./sql:/sql
  db:
    image: postgres
    environment:
      POSTGRES_USER: adventurelog
      POSTGRES_PASSWORD: PO24VjITwGgk
      POSTGRES_DB: adventurelog
    ports:
      - "5432:5432"
