version: "3.9"

services:
  web:
    build:
      context: ./frontend/
    environment:
      - PUBLIC_SERVER_URL=http://server:8000
      - ORIGIN=http://localhost:8080
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - "8080:3000"
    depends_on:
      - server

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: changeme123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    build: ./backend/
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=changeme123
      - SECRET_KEY=changeme123
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL='http://127.0.0.1:8000'
      - DEBUG=False
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - adventurelog_media:/code/media/

volumes:
  postgres_data:
  adventurelog_media:
