services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://adventurelog:PO24VjITwGgk@db:5432/adventurelog
      # ORIGIN is only necessary when not using a reverse proxy or hosting that includes https
      - ORIGIN=http://localhost:3000
      - SKIP_DB_WAIT=false
      - MINIO_SERVER_URL=minio
      - MINIO_CLIENT_URL=http://localhost:9000
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - BODY_SIZE_LIMIT=Infinity
      # Only necessary for externally hosted databases such as NeonDB
    depends_on:
      - db
      - minio
  db:
    image: postgres
    environment:
      POSTGRES_USER: adventurelog
      POSTGRES_PASSWORD: PO24VjITwGgk
      POSTGRES_DB: adventurelog
    ports:
      - "5432:5432"
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  minio_data:
